version: "3.8"
services:
  web-front:
    build:
      dockerfile: Dockerfile
#    container_name:
    networks:
      - app-network
    volumes:
      - ./:/app:cached
      - ./node_modules:/app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://host.docker.internal/api
    expose:
      - 5173
    ports:
      - "5173:5173"
    command: npm run dev

networks:
  app-network:
    driver: bridge